---
sudo: false
addons:
  apt:
    packages: []
  coverity_scan:
    project:
      description: Build submitted via Travis CI
      name: maxmind/MaxMind-DB-Reader-php
    notification_email: dev-ci@maxmind.com
    build_command: ./.travis-build.sh
    branch_pattern: .*coverity.*
language: php
dist: trusty
matrix:
  include:
    - php: '5.6'
    - php: '7.0'
    - php: '7.1'
    - php: '7.2'
    - php: '7.3'
      env:
        - RUN_LINTER=1
        - RUN_SNYK=1
    - php: '7.4snapshot'
    - php: 'master'
    - php: 'nightly'
  fast_finish: true
  allow_failures:
    - php: '7.4snapshot'
    - php: 'master'
    - php: 'nightly'

env:
  global:
    - secure: "RMIBN2tNKlrGA07coRW4B9m9jCobrYxDkEq3T3jGoGtXgQe/Mr3bI/4zQo7U3bvVTSF90lzkWbxATY45GQXRxWC7Ed2HI2jwUF96CXecdRhKiE9x051HsvXakvbODPLocV7/2LOZqz+eXCUeazLgRaSrIhAqMddFqMQSSM5STlc="
    - secure: "c/961zYzYtZlUK4wznM6xzvk0fmVTYKRQc1FkWcBZTU6sSnq+8iGYc58HVFDcZQfe6pOTdGXd4rUyWwQFPnXegYVv7tFsmKWqofejaWDdzkF6gYJSd8CLOUF4oeunoUO4NM9nbQRDURd/iekXeeryyNjw1YNAbmNhIXr5zzeHrs="
before_install:
  - ./.travis-install-prereqs.sh
  - "if [[ $RUN_SNYK && $SNYK_TOKEN ]]; then sudo apt-get install -y nodejs; npm install -g snyk; fi"
install:
  - ./.travis-build.sh
  - phpenv rehash
  - "if [[ $RUN_SNYK && $SNYK_TOKEN ]]; then snyk test --org=maxmind; fi"
script:
  - ./.travis-test.sh
after_script:
  - php vendor/bin/coveralls
after_success:
  - "if [[ $RUN_SNYK && $SNYK_TOKEN && $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then snyk monitor --org=maxmind --project-name=maxmind/MaxMind-DB-Reader-php; fi"
notifications:
  email:
    on_failure: always
    on_success: change
    recipients:
      - dev-ci@maxmind.com
  slack:
    rooms:
      secure: "J8nDFLo1+6wWPyYcO2fdUF5w8soZa5mcTYhoa8HA+GUfVGFe7L63ruHBjbEhySG4tQBXJ7oh8ETIyS6hKLNLXdBOSYAQyrZa54HrTxTR1FXPoBiNqPi5DlUIxmJiGxWNp3Yh+0UXFg3otkKtDAjXg1JCoW+XNBsoMw6NqUmkH5Q=\n"
